import type { GameEvent } from "./game-data.ts";

const hidden = (
  id: string,
  title: string,
  result: string,
  effects: GameEvent["choices"][number]["effects"],
) => ({ id, title, preview: "", result, effects });

export const causalLifeEvents: GameEvent[] = [
  {
    id: "keepsake-camera-first-roll",
    phase: "weekly",
    label: "道具支线 · 第一卷胶片",
    title: "训练结束得比预计早，窗外还剩一段真正的夕阳。",
    body: [
      "相机买来以后一直躺在抽屉里，谁都觉得应该等到更重要的日子。今天没有获奖、没有人退队，也没有任何仪式；只是教室难得提前安静，桌面上摊着吃剩的面包和还没订正完的卷子。有人发现相机，提议趁所有人都在拍一张。二十七格底片忽然显得很多，又显得经不起随便浪费。",
    ],
    concealConsequences: true,
    archive: { category: "日常生活", group: "道具支线 · 胶片相机", clusterKey: "keepsake-camera-first-roll", order: 1, timingNote: "购买一次性胶片相机后，普通训练周触发" },
    causality: { chainId: "keepsake-camera", step: 1 },
    trigger: { earliestWeek: 8, latestWeek: 72, requiredTags: ["shop:instant-camera"], probability: 0.62 },
    choices: [
      hidden("camera-join", "把桌椅推开，和所有人挤进同一张照片", "你们花了很久才找到能放下相机的位置，倒计时响起时还有人弯腰去捡掉在地上的笔。快门记录的不是整齐队形，而是几个人同时抬头、有人闭眼、有人仍举着半块面包的瞬间。照片尚未冲洗，你已经知道它不会像宣传栏上的合影，却也因此只属于这间教室真正存在过的一个傍晚。", { peerFavor: 2, san: 2, tags: ["camera:first:joined"] }),
      hidden("camera-take", "留在镜头外，替他们按下快门", "你把大家的位置调整好，提醒最边上的人往里站，然后在倒计时结束前没有跑回队伍。取景框里的人笑得很放松，因为有人负责确认画面；快门落下后，他们才意识到照片里没有你。有人说下一张一定换人拍，你却没有立刻答应。缺席同样会被胶片忠实保存，只是当时没人知道它以后会怎样被解释。", { social: 1, san: 1, tags: ["camera:first:outside"] }),
      hidden("camera-save", "先不拍，把这一格留给真正重要的日子", "相机被重新放回抽屉，夕阳在几分钟后完全离开窗台。大家没有责怪你，只继续收拾桌面，仿佛刚才那段提议从未发生。底片确实被节省下来，代价是这个普通傍晚不会再以同样阵容回来；你也第一次意识到，等待重要时刻有时只是让日常不断从身边无声经过。", { mindset: 1, tags: ["camera:first:saved"] }),
    ],
  },
  {
    id: "keepsake-camera-developed-joined",
    phase: "weekly",
    label: "道具支线 · 冲洗出来的人",
    title: "相纸从纸袋里滑出来，你先看见自己闭着一只眼。",
    body: ["冲洗店拖了很久，照片回来时，原先坐在教室里的队员已经有人停训、有人去外地集训，也有人仍每天出现。画面里的桌椅凌乱得近乎难看，你却能准确指出每个人当时刚做完哪套题。照片没有替关系保持原样，只让变化拥有了一张可以反复对照的底片。"],
    concealConsequences: true,
    archive: { category: "日常生活", group: "道具支线 · 胶片相机", clusterKey: "keepsake-camera-developed", variantKey: "joined", variantLabel: "进入合影", order: 2 },
    causality: { chainId: "keepsake-camera", step: 2, requiresEvents: ["keepsake-camera-first-roll"], minimumWeeksAfterEvents: { "keepsake-camera-first-roll": 5 }, maximumWeeksAfterEvents: { "keepsake-camera-first-roll": 24 }, closesChain: true },
    trigger: { earliestWeek: 16, latestWeek: 100, requiredTags: ["camera:first:joined"], probability: 0.75 },
    choices: [
      hidden("camera-developed-share", "把照片扫描后发给当时在场的每个人", "你没有写长篇感言，只按记忆把原图分别发出去。最先回复的是已经离队的人，TA问起桌角那盆植物是否还活着；仍在训练的人则开始争论谁当时偷吃了最后一块面包。短短几条消息没有恢复原来的队伍，却让已经断开的联系获得一次不以成绩为理由的重新开场。", { social: 2, peerFavor: 2, san: 2, tags: ["memory:team-photo-shared"] }),
      hidden("camera-developed-keep", "把唯一一张原片夹进笔记本，不发给任何人", "你把照片夹在最常用的笔记本末页，只有翻到很后面才会看见。没有人知道你保留了它，也没人因此获得重新联系的机会。偶尔复习到那一章时，画面会短暂出现：不是为了证明那段关系仍然亲密，而是确认自己确实曾经属于过那个杂乱、短暂且无法复制的傍晚。", { san: 3, mindset: 2, tags: ["memory:team-photo-private"] }),
    ],
  },
  {
    id: "keepsake-camera-developed-outside",
    phase: "weekly",
    label: "道具支线 · 镜头外的人",
    title: "照片冲洗出来以后，所有人都在，除了按快门的你。",
    body: ["有人把照片传进群里，直到讨论谁闭眼时才发现你没有入镜。当时那句‘下一张换人拍’早已被训练、考试和人员变动挤走。没有人故意排除你，结果却与被排除非常相似：你保存了所有人的样子，自己的位置只存在于拍摄角度和他们朝向镜头的目光里。"],
    concealConsequences: true,
    archive: { category: "日常生活", group: "道具支线 · 胶片相机", clusterKey: "keepsake-camera-developed", variantKey: "outside", variantLabel: "留在镜头外", order: 2 },
    causality: { chainId: "keepsake-camera", step: 2, requiresEvents: ["keepsake-camera-first-roll"], minimumWeeksAfterEvents: { "keepsake-camera-first-roll": 5 }, maximumWeeksAfterEvents: { "keepsake-camera-first-roll": 24 }, closesChain: true },
    trigger: { earliestWeek: 16, latestWeek: 100, requiredTags: ["camera:first:outside"], probability: 0.75 },
    choices: [
      hidden("camera-outside-ask", "约还在学校的人补拍一张，不再负责按快门", "你把缺席指出来，没有用玩笑替大家解围。补拍那天少了两名已经离队的人，光线也不如从前，但这次你站在最中间，把相机交给路过的老师。新照片不能修复旧照片的空位，却让你停止等待别人主动发现：想被留下并不等于索取特殊照顾，有时只是明确走进画面。", { social: 3, peerFavor: 1, mindset: 2, tags: ["memory:asked-to-be-seen"] }),
      hidden("camera-outside-accept", "保留这张照片，也接受自己当时选择了镜头外", "你没有补拍，也没有把缺席解释成谁的过错。当时是你决定替所有人确认画面，而照片只是把这个决定保存得比记忆更久。承认主动选择并没有消除一点失落，却让你不必把它改写成被抛下的证据。你在相纸背面写下日期，也写上拍摄者的名字。", { san: 2, mindset: 3, tags: ["memory:camera-role-accepted"] }),
    ],
  },
  {
    id: "keepsake-letter-first",
    phase: "weekly",
    label: "道具支线 · 没有收件人的信",
    title: "信纸买回来一周，你仍然没有决定要写给谁。",
    body: ["它可以写给省赛后的自己、已经疏远的人、家长，或者此刻无法承认可能失败的你。晚自习结束后，教室只剩台灯和走廊尽头的脚步声。写下来的句子不会立刻改变任何关系，却可能在很久以后成为无法撤回的证词；继续空着，则让所有可能都保持安全。"],
    concealConsequences: true,
    archive: { category: "日常生活", group: "道具支线 · 信纸", clusterKey: "keepsake-letter-first", order: 1 },
    causality: { chainId: "keepsake-letter", step: 1 },
    trigger: { earliestWeek: 12, latestWeek: 64, requiredTags: ["shop:letter-set"], probability: 0.58 },
    choices: [
      hidden("letter-future", "写给第二次联赛结束后的自己", "你没有要求未来的自己必须成功，只写下现在掌握到哪里、在害怕什么，以及如果没有进入省队最想先做的一件普通小事。信封被封住以后，失败第一次不再只是一团不能触碰的黑影，而成为某个具体的人可能收到的一封信。你把开封日期写在背面，没有给提前偷看的自己留借口。", { mindset: 2, san: -1, tags: ["letter:future-self"] }),
      hidden("letter-family", "写给一直想解释却没能说完的父母", "你没有把信写成控诉，也没有替父母总结苦心，只逐段记录哪些支持让你感激、哪些询问使你喘不过气，以及自己为什么仍然舍不得离开。写完后你没有立刻交出去，因为此刻的家里未必能完整听完。文字先替你保存边界，等待一个不需要争夺发言顺序的晚上。", { familySupport: 0.5, san: -2, tags: ["letter:family"] }),
      hidden("letter-blank", "把日期写好，仍然留下一张白纸", "你只在右上角写下日期，随后把纸折好放回信封。空白并不比文字更虚假：它记录了这一天你确实有很多话，却没有找到足以承担后果的排列方式。以后打开时，你可能庆幸没有冲动落笔，也可能再也想不起当初想说什么；两种损失都属于保留沉默的代价。", { san: 2, tags: ["letter:blank"] }),
    ],
  },
  {
    id: "keepsake-letter-open-future",
    phase: "weekly",
    label: "道具支线 · 到期开封",
    title: "第二次联赛已经结束，信封上的日期没有替你判断结果好坏。",
    body: ["你认得那时刻意写得平稳的字，也记得每一句背后没有写出的恐惧。现在的路线也许比预想更好，也许已经转向高考，但信里的你并不知道答案，只认真留下了一个失败之后仍想完成的小愿望。"],
    concealConsequences: true,
    archive: { category: "日常生活", group: "道具支线 · 信纸", clusterKey: "keepsake-letter-open", variantKey: "future", variantLabel: "写给未来的自己", order: 2 },
    causality: { chainId: "keepsake-letter", step: 2, requiresEvents: ["keepsake-letter-first"], minimumWeeksAfterEvents: { "keepsake-letter-first": 10 }, maximumWeeksAfterEvents: { "keepsake-letter-first": 50 }, closesChain: true },
    trigger: { earliestWeek: 48, latestWeek: 104, requiredTags: ["letter:future-self"], probability: 0.85 },
    choices: [
      hidden("letter-future-do", "先去完成信里那件与竞赛无关的小事", "你没有等到所有安排结束，便抽出半天去做那件当时写下的小事。它可能只是看一场电影、走一段旧路或睡到自然醒，完成后也没有让失利变轻、让奖牌更亮。可过去的自己提出过一个不以成绩为条件的请求，而你没有因为路线已经改变就把TA当成不成熟的人。", { san: 5, mindset: 3, tags: ["memory:kept-promise-to-self"] }),
      hidden("letter-future-reply", "在原信背面写一封回信，再次封存", "你告诉过去的自己哪些担心成真、哪些完全没有发生，也承认现在仍有新的问题。回信没有使用‘一切都会好起来’这样的结论，因为你已经知道未来只会变得更具体。两层字迹叠在同一张纸上，像一次跨越数月的对话：没有谁更正确，只是承担着不同阶段能看见的部分。", { reasoning: 0.5, mindset: 4, san: 1, tags: ["memory:answered-past-self"] }),
    ],
  },
  {
    id: "keepsake-letter-open-family",
    phase: "weekly",
    label: "道具支线 · 把信放到餐桌上",
    title: "那封信没有找到完美时机，只等到一个没有人急着出门的晚上。",
    body: ["纸上的情绪来自几个月前，家里的关系却已经发生变化。有些抱怨如今不再适用，有些感谢当时说不出口，现在读来反而更加明确。把旧信交出去并不等于要求父母为过去受审；继续保留，也意味着那些话可能永远只由写信的人知道。"],
    concealConsequences: true,
    archive: { category: "家庭与教练", group: "道具支线 · 信纸", clusterKey: "keepsake-letter-open", variantKey: "family", variantLabel: "写给父母", order: 2 },
    causality: { chainId: "keepsake-letter", step: 2, requiresEvents: ["keepsake-letter-first"], minimumWeeksAfterEvents: { "keepsake-letter-first": 6 }, maximumWeeksAfterEvents: { "keepsake-letter-first": 40 }, closesChain: true },
    trigger: { earliestWeek: 24, latestWeek: 100, requiredTags: ["letter:family"], probability: 0.72 },
    choices: [
      hidden("letter-family-give", "把原信交给父母，不补写更体面的版本", "父母轮流读完，中间几次想解释，又因为你事先要求而忍住。信里的某些判断让他们难过，也有些细节是他们第一次知道。谈话没有立刻和解，至少不再围绕谁记错了某句话争执；文字把当时的你留在桌面上，迫使所有人承认那份感受曾真实存在。", { familySupport: 3, social: 2, san: -2, tags: ["memory:family-letter-delivered"] }),
      hidden("letter-family-keep", "把信读给自己听，然后重新收好", "你没有把信交出去，只在空房间里完整读了一遍。几个月后的你会删掉某些过重的指责，也会发现有些边界至今仍需要坚持。沉默没有自动变成原谅，交付也不再是唯一证明勇敢的方式；你留下信，准备以后用现在的语言谈，而不是要求旧文字替你完成全部沟通。", { mindset: 3, san: 2, tags: ["memory:family-letter-kept"] }),
    ],
  },
  {
    id: "keepsake-labels-field-note",
    phase: "weekly",
    label: "道具支线 · 标签上的地点",
    title: "校园角落的昆虫样本没有名字，只有一张被雨泡开的旧纸条。",
    body: ["它可能是上一届留下的观察记录，也可能只是某次临时采集忘了处理。防水标签刚好能补上日期、地点和环境，但重新编号意味着你将接手一个来源不完整的样本；把它丢掉更规范，却也会让唯一可追溯的地点信息彻底消失。"],
    concealConsequences: true,
    archive: { category: "日常生活", group: "道具支线 · 标本标签", clusterKey: "keepsake-labels-field-note", order: 1 },
    causality: { chainId: "keepsake-labels", step: 1 },
    trigger: { earliestWeek: 14, latestWeek: 78, requiredTags: ["shop:specimen-labels"], probability: 0.55 },
    choices: [
      hidden("labels-reconstruct", "保留未知标记，重新调查采集地点", "你没有擅自补全物种名，而是在新标签上写明‘原记录受损’，随后按地点回到校园角落。相同环境里找到了几只形态接近的个体，也发现旧纸条上的月份可能抄错。记录因此比直接猜名更慢，却把不确定性完整保留下来；样本第一次拥有可以被后来者重新核查的来路。", { module2: 0.8, reasoning: 0.8, san: -1, tags: ["labels:reconstructed"] }),
      hidden("labels-discard", "按来源不明样本处理，只留下旧标签照片", "你没有让一个来源残缺的样本混进正式收藏，拍照登记后按规范处理。那张旧纸条可能对应稀有记录，也可能只是常见物种；以后都无法证明。选择丢弃保住了资料库的可信度，也承认科学记录有时必须接受不可追回，而不是用一个看似完整的名称遮住缺口。", { reasoning: 1, mindset: 1, tags: ["labels:discarded"] }),
    ],
  },
  {
    id: "keepsake-labels-return",
    phase: "weekly",
    label: "道具支线 · 记录回到抽屉",
    title: "上一届队员回校取资料，一眼认出了那张泡开的旧标签。",
    body: ["TA记得采集经过，却无法保证日期和地点都准确；当时的记录本已经丢失，只剩零散印象。你手里的新标签比记忆更规范，却必须决定是否把后来调查与原作者口述合并。两份证据都不完整，谁也不能只凭资历获得优先权。"],
    concealConsequences: true,
    archive: { category: "日常生活", group: "道具支线 · 标本标签", clusterKey: "keepsake-labels-return", order: 2 },
    causality: { chainId: "keepsake-labels", step: 2, requiresEvents: ["keepsake-labels-field-note"], minimumWeeksAfterEvents: { "keepsake-labels-field-note": 4 }, maximumWeeksAfterEvents: { "keepsake-labels-field-note": 26 }, closesChain: true },
    trigger: { earliestWeek: 22, latestWeek: 100, requiredTags: ["labels:reconstructed"], probability: 0.7 },
    choices: [
      hidden("labels-return-layer", "把口述作为附注，不覆盖重新调查结果", "你请TA逐项说出确定与不确定的部分，把记忆记录在另一张标签上，与后来调查并列保存。旧队员有些尴尬，却承认当年只想赶在放假前收尾。两套记录没有被强行统一，反而清楚展示证据如何在时间里损失；这个样本最终最有价值的部分，成了它留下的记录方法。", { reasoning: 1.2, module2: 0.8, coachFavor: 0.5, tags: ["memory:layered-evidence"] }),
      hidden("labels-return-owner", "把样本和调查记录一并交还原采集者", "你把样本、照片和新记录全部交还，没有要求它必须留在学校收藏。TA答应整理后补回资料，却未必真的会做。归还尊重了原采集者与那段经历的联系，也让公共记录失去一次可能完善的机会；你保留电子副本，承认资料所有权与科学可追溯性并不总能自然重合。", { social: 1.5, san: 1, tags: ["memory:sample-returned"] }),
    ],
  },
  {
    id: "keepsake-bus-last-run",
    phase: "weekly",
    label: "道具支线 · 末班车",
    title: "训练楼关门时，常坐的那班公交刚从站牌前驶过。",
    body: ["下一班是末班车，需要等四十分钟；步行回宿舍更快，却会经过一段没有路灯的旧路。卡套里的停运时刻表让你想起刚入队时总有人一起等车，如今同一时间离开的人越来越少。今晚没有突发大事，只是城市交通把独处突然拉长。"],
    concealConsequences: true,
    archive: { category: "日常生活", group: "道具支线 · 公交卡套", clusterKey: "keepsake-bus-last-run", order: 1 },
    causality: { chainId: "keepsake-bus", step: 1 },
    trigger: { earliestWeek: 10, latestWeek: 80, requiredTags: ["shop:old-bus-card"], probability: 0.56 },
    choices: [
      hidden("bus-wait", "留在站台等末班车，给很久没联系的人发条消息", "你没有为联系寻找正式理由，只问对方最近是否还坐这条线路。消息过了十几分钟才回复，内容也很普通，却把彼此从只会在成绩公布时出现的关系里暂时拉出来。末班车到站时，你们刚聊到车窗冬天总起雾；没有人承诺恢复从前，至少这次联系不是为了索取资料或确认排名。", { social: 2, san: 1, tags: ["bus:reconnected"] }),
      hidden("bus-walk", "沿旧路走回去，把四十分钟留给自己", "你打开手机照明，沿着刚入队时走过的路慢慢回去。几家店已经换了招牌，曾经一起等车的人也不再出现在固定时间。步行没有制造新的关系，却让你在没有训练、聊天和排名的四十分钟里重新感到身体正在穿过一座真实城市；独处并不总是被落下，也可能是主动收回时间。", { san: 3, mindset: 2, tags: ["bus:walked-alone"] }),
    ],
  },
  {
    id: "keepsake-bus-route-return",
    phase: "weekly",
    label: "道具支线 · 旧路线",
    title: "几个月后，那条线路调整站点，你们约在已经不用再去的旧站牌见面。",
    body: ["重新联系没有让关系回到从前。对方有了新的课表和朋友，你也不再熟悉TA每天抱怨的细节。旧卡套仍能证明你们曾在这里等过很多次车，却不能要求今天的谈话自动亲密。你们需要决定，是用回忆填满见面，还是从不再相同的近况重新认识。"],
    concealConsequences: true,
    archive: { category: "人物关系", group: "道具支线 · 公交卡套", clusterKey: "keepsake-bus-route-return", order: 2 },
    causality: { chainId: "keepsake-bus", step: 2, requiresEvents: ["keepsake-bus-last-run"], minimumWeeksAfterEvents: { "keepsake-bus-last-run": 6 }, maximumWeeksAfterEvents: { "keepsake-bus-last-run": 30 }, closesChain: true },
    trigger: { earliestWeek: 24, latestWeek: 104, requiredTags: ["bus:reconnected"], probability: 0.72 },
    choices: [
      hidden("bus-return-memory", "沿原路线走一遍，把旧事说到自然结束", "你们逐个认出曾经躲雨、买夜宵和争论答案的地方，也发现很多细节只剩一个人记得。回忆并没有把关系锁回原样，反而在说完后腾出空白。走到终点时，你们没有约定下周再见，只承认这段共同路线确实存在过，而且结束并不会使它变成虚假。", { san: 3, social: 2, tags: ["memory:route-farewell"] }),
      hidden("bus-return-present", "不再沿旧路走，去对方现在常去的地方", "你把旧站牌留在身后，请对方带路去最近才发现的小店。新话题几次停顿，也没有从前那种不必解释的默契，却让你们开始知道彼此现在怎样生活。修复并不是反复证明旧日亲密，而是允许双方不再是记忆里的版本；这次见面之后，关系仍可能淡去，也可能长出新的理由。", { social: 3, peerFavor: 1.5, mindset: 2, tags: ["memory:relationship-renewed"] }),
    ],
  },
];

export const causalLifeDeveloperCatalog = causalLifeEvents;
